#!/usr/bin/env python3
"""
Based on the grid data generated by render_block.py (matrix.json / optional color.json),
build JSON descriptions for the "left view / front view / top view" of each sample.

View description
--------
- The coordinate system used for the orthographic three views is described:
  - left view: the horizontal axis is y, the vertical axis is z, the depth axis is x
  - front view: the horizontal axis is x, the vertical axis is z, the depth axis is y
  - top view: the plane is (x, y), the vertical axis is z
- Each 3D block is whether "visible" / "occluded", reuse the result of utils.generate_voxel_matrix
  in the isometric view (left-view-45.png):
    - voxels[x][y][z] == 1  -> visible=True,  occluded=False
    - voxels[x][y][z] == -1 -> visible=False, occluded=True
    - voxels[x][y][z] == 0  -> air, will not be output as a block

Output location
--------
- For each case directory (levelXXX/N) in the input root directory:
  - Write a JSON file (default: view_desc.json) in the case directory

Running example
--------
Run from the project root directory, for example:

python geo-synthetic/block-count-synthetic/build_cube_views_json.py \
    --input-dir geo-synthetic/block-count-synthetic/OUTPUT_COLOR

Or run in the directory where the script is located:

  python build_cube_views_json.py --input-dir OUTPUT_COLOR
"""

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from utils import generate_voxel_matrix


# The same color mapping as in build_cube_counting_color_dataset.py
COLOR_ID_TO_NAME = {
    1: "black",
    2: "white",
    3: "red",
    4: "yellow",
    5: "blue",
    6: "green",
}


def load_height_matrix(case_dir: Path) -> Optional[List[List[int]]]:
    """Load the height matrix matrix.json in a case."""
    path = case_dir / "matrix.json"
    if not path.exists():
        print(f"Warning: {path} does not exist, skip this case")
        return None
    try:
        with path.open("r", encoding="utf-8") as f:
            h = json.load(f)
        return h
    except Exception as e:
        print(f"Error: failed to read {path}: {e}, skip this case")
        return None


def load_color_matrix(case_dir: Path) -> Optional[List[List[List[int]]]]:
    """Load the color matrix color.json in a case, if not exist, return None."""
    path = case_dir / "color.json"
    if not path.exists():
        return None
    try:
        with path.open("r", encoding="utf-8") as f:
            color_matrix = json.load(f)
        return color_matrix
    except Exception as e:
        print(f"Error: failed to read {path}: {e}, ignore color information")
        return None


def compute_shape(h: List[List[int]]) -> Dict[str, int]:
    """
    Calculate the grid size:
    - C: x direction length (outer index)
    - R: y direction length (inner index)
    - H: maximum height
    """
    C = len(h)
    R = len(h[0]) if C > 0 else 0
    H = 0
    for x in range(C):
        for y in range(R):
            val = h[x][y]
            if val > H:
                H = val
    return {"C": C, "R": R, "H": H}


def get_color_info(
    color_matrix: Optional[List[List[List[int]]]],
    x: int,
    y: int,
    z: int,
) -> Dict[str, Any]:
    """Safely get the color information at (x, y, z) from the color_matrix."""
    info: Dict[str, Any] = {}
    if color_matrix is None:
        return info

    if y < len(color_matrix) and x < len(color_matrix[y]) and z < len(color_matrix[y][x]):
        color_id = color_matrix[y][x][z]
        if color_id > 0:
            info["color_id"] = color_id
            if color_id in COLOR_ID_TO_NAME:
                info["color_name"] = COLOR_ID_TO_NAME[color_id]
    return info


def build_left_view(
    h: List[List[int]],
    voxels: List[List[List[int]]],
    color_matrix: Optional[List[List[List[int]]]],
) -> Dict[str, Any]:
    """
    Build the JSON description of the left orthographic view.

    Agreement:
    - Fixed y, the vertical axis is z, from bottom to top (0 -> H-1)
    - The depth axis is x, assuming the camera is located at +x direction looking at the origin
      For a given (y, z), only the first visible block encountered along the x-axis from near to far is retained
    """
    shape = compute_shape(h)
    C, R, H = shape["C"], shape["R"], shape["H"]

    left: Dict[str, Any] = {
        "view_type": "left",
        "columns": [],  # Each element corresponds to a y
    }

    if C == 0 or R == 0 or H == 0:
        return left

    for y in range(R):
        column: Dict[str, Any] = {
            "y": y,
            "layers": [],  # Each element corresponds to a height z, only containing the first block on the line of sight (visible or occluded)
        }
        for z in range(H):
            # Traverse from x maximum, simulate the camera looking from the +x direction
            visible_block: Optional[Dict[str, Any]] = None
            for x in range(C - 1, -1, -1):
                col_height = h[x][y]
                if z >= col_height:
                    continue  # There is no block at this height

                state = voxels[x][y][z]
                block: Dict[str, Any] = {
                    "x": x,
                    "y": y,
                    "z": z,
                    # Whether visible/occluded in the isometric view
                    "visible": state == 1,
                    "occluded": state == -1,
                    "order": 0,
                }
                block.update(get_color_info(color_matrix, x, y, z))
                visible_block = block
                break

            if visible_block is not None:
                layer = {
                    "z": z,
                    "blocks": [visible_block],
                }
                column["layers"].append(layer)

        left["columns"].append(column)

    return left


def build_front_view(
    h: List[List[int]],
    voxels: List[List[List[int]]],
    color_matrix: Optional[List[List[List[int]]]],
) -> Dict[str, Any]:
    """
    Build the JSON description of the front orthographic view.

    Agreement:
    - Fixed x, the vertical axis is z, from bottom to top (0 -> H-1)
    - The depth axis is y, assuming the camera is located at +y direction looking at the origin
      For a given (x, z), only the first visible block encountered along the y-axis from near to far is retained
    """
    shape = compute_shape(h)
    C, R, H = shape["C"], shape["R"], shape["H"]

    front: Dict[str, Any] = {
        "view_type": "front",
        "columns": [],  # Each element corresponds to a x
    }

    if C == 0 or R == 0 or H == 0:
        return front

    for x in range(C):
        column: Dict[str, Any] = {
            "x": x,
            "layers": [],  # Each element corresponds to a height z, only containing the first block on the line of sight (visible or occluded)
        }
        for z in range(H):
            # Traverse from y maximum, simulate the camera looking from the +y direction
            visible_block: Optional[Dict[str, Any]] = None
            for y in range(R - 1, -1, -1):
                col_height = h[x][y]
                if z >= col_height:
                    continue

                state = voxels[x][y][z]
                block: Dict[str, Any] = {
                    "x": x,
                    "y": y,
                    "z": z,
                    "visible": state == 1,
                    "occluded": state == -1,
                    "order": 0,
                }
                block.update(get_color_info(color_matrix, x, y, z))
                visible_block = block
                break

            if visible_block is not None:
                layer = {
                    "z": z,
                    "blocks": [visible_block],
                }
                column["layers"].append(layer)

        front["columns"].append(column)

    return front


def build_top_view(
    h: List[List[int]],
    voxels: List[List[List[int]]],
    color_matrix: Optional[List[List[List[int]]]],
) -> Dict[str, Any]:
    """
    Build the JSON description of the top orthographic view.

    Agreement:
    - Each (x, y) position is a column from bottom to top
    - Only the highest block in the column (possibly visible or occluded in the isometric view) is retained
    """
    shape = compute_shape(h)
    C, R, H = shape["C"], shape["R"], shape["H"]

    top: Dict[str, Any] = {
        "view_type": "top",
        "cells": [],  # Each element corresponds to a (x, y)
    }

    if C == 0 or R == 0 or H == 0:
        return top

    for x in range(C):
        for y in range(R):
            col_height = h[x][y]
            if col_height <= 0:
                continue

            # Traverse from the highest layer to find the first real block (z < col_height)
            visible_block: Optional[Dict[str, Any]] = None
            for z in range(col_height - 1, -1, -1):
                state = voxels[x][y][z]
                if state == 0:
                    continue

                block: Dict[str, Any] = {
                    "z": z,
                    "visible": state == 1,
                    "occluded": state == -1,
                }
                block.update(get_color_info(color_matrix, x, y, z))
                visible_block = block
                break

            if visible_block is not None:
                cell = {
                    "x": x,
                    "y": y,
                    "layers": [visible_block],
                }
                top["cells"].append(cell)

    return top


def resolve_input_root(arg_path: str) -> Path:
    """
    Parse the input root directory:
    - If arg_path is an absolute path or exists relative to the current working directory, use it directly
    - Otherwise, try to resolve it relative to the directory where the script is located
    """
    raw = Path(arg_path)
    if raw.is_absolute() or raw.exists():
        return raw

    script_dir = Path(__file__).parent
    alt = script_dir / arg_path
    return alt


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the JSON description of the three views based on matrix.json / color.json"
    )
    parser.add_argument(
        "--input-dir",
        type=str,
        required=True,
        help="The root directory of the output of render_block.py, for example OUTPUT_DIR or geo-synthetic/block-count-synthetic/OUTPUT_COLOR",
    )
    parser.add_argument(
        "--output-filename",
        type=str,
        default="view_desc.json",
        help="The JSON file name for each case, default: view_desc.json",
    )

    args = parser.parse_args()

    input_root = resolve_input_root(args.input_dir)
    if not input_root.exists() or not input_root.is_dir():
        print(f"Error: the input directory {input_root} does not exist or is not a directory")
        return

    # Find the level directories
    level_dirs = sorted(
        [d for d in input_root.iterdir() if d.is_dir() and d.name.startswith("level")]
    )
    if not level_dirs:
        print(f"Error: no level* directories found in {input_root}")
        return

    print(f"Found {len(level_dirs)} level directories: {[d.name for d in level_dirs]}")

    total_cases = 0
    for level_dir in level_dirs:
        print(f"\nProcessing {level_dir.name} ...")
        # The case directory is a pure number name
        case_dirs = sorted(
            [d for d in level_dir.iterdir() if d.is_dir() and d.name.isdigit()],
            key=lambda p: int(p.name),
        )
        print(f"  {len(case_dirs)} cases")

        for case_dir in case_dirs:
            case_id = f"{level_dir.name}_{case_dir.name}"

            h = load_height_matrix(case_dir)
            if h is None:
                continue

            voxels = generate_voxel_matrix(h)
            if not voxels:
                print(f"  Warning: failed to generate the visibility matrix for {case_id}, skip")
                continue

            color_matrix = load_color_matrix(case_dir)

            shape = compute_shape(h)
            left_view = build_left_view(h, voxels, color_matrix)
            front_view = build_front_view(h, voxels, color_matrix)
            top_view = build_top_view(h, voxels, color_matrix)

            record: Dict[str, Any] = {
                "id": case_id,
                "shape": shape,
                "has_color": color_matrix is not None,
                "views": {
                    "left": left_view,
                    "front": front_view,
                    "top": top_view,
                },
            }

            out_path = case_dir / args.output_filename
            try:
                with out_path.open("w", encoding="utf-8") as f:
                    json.dump(record, f, ensure_ascii=False, indent=2)
            except Exception as e:
                print(f"  Error: failed to write to {out_path}: {e}")
                continue

            total_cases += 1

    print(f"\nDone! Generated {total_cases} cases of three view JSON descriptions.")


if __name__ == "__main__":
    main()


